### PR TITLE
Limiting planets selectable when sowing cache

### PR DESCRIPTION
**Pull request by Klensor**
Addresses issue  #215

Returns right number of options if 'PlanetCount' is available from wh_systems, otherwise the standard default.

I wasn't sure exactly where to put the function - I'm still finding my feet with the php stuff but putting code into the modal_sow file felt a bit untidy, however the systems class is very db focused.

### CODE REVIEW

**Comment by bikerunner** [comment]
Would it be useful to provide an SQL statement to update the table with the new column and set a default value (current max planet number)? So it's possible to set the planet count later? It will be a separate issue otherwise.

**Comment by Klensor** [comment]
> 
> 
> Would it be useful to provide an SQL statement to update the table with the new column and set a default value (current max planet number)? So it's possible to set the planet count later? It will be a separate issue otherwise.

ALTER TABLE `wh_systems` ADD `PlanetCount` TINYINT NOT NULL DEFAULT '20' AFTER `Notes`;

**Comment by Klensor** [comment]
This is the updated file including the missing entry (total 2603 rows)

[UpdatePlanetCounts.zip](https://github.com/Thricehappy/EveScoutRescue/files/3224240/UpdatePlanetCounts.zip)

**Comment by bikerunner** [comment]
@Thricehappy This works for me. Tested at local installation.

Update procedure for database:
* backup database
* apply provided SQL statement 'ALTER TABLE wh_systems ADD PlanetCount TINYINT NOT NULL DEFAULT '20' AFTER Notes;'
* apply content of UpdatePlanetCounts.zip to the database

**Comment by Thricehappy** [comment]
All changes pushed to production.

**Pull request merged**
