### PR TITLE
Simplify search paget

### PR DESCRIPTION
**Pull request by bikerunner**
- reduce mix of php and html code
- move db queries from search.php to separate class files

### CODE REVIEW

**Comment by bikerunner** [comment]
Issue #43

**Comment by Thricehappy** [comment]
I pulled this to test. First thing I notice is the following error on search.php:

Fatal error: Default value for parameters with a class type hint can only be NULL in C:\xampp\htdocs\EveScoutRescue\class\leaderboard.class.php on line 19

I can't move beyond that, and I don't know what this means. Can you look into this and advise? Thanks!

**Comment by bikerunner** [comment]
It's strange that I did not get the same error. Tested with a 7.0 and 7.1 PHP version. :(

 

I applied changes to the class and removed the default value definition for the moment. This seems to be the issue regarding the net.

 

The PR is updated automatically. Feel free to try again. The IP column change is already merged to the PR.

 

Klaus

 

Gesendet: Donnerstag, 20. April 2017 um 19:32 Uhr
Von: Thricehappy <notifications@github.com>
An: Thricehappy/EveScoutRescue <EveScoutRescue@noreply.github.com>
Cc: bikerunner <k.m@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [Thricehappy/EveScoutRescue] Simplify search paget (#45)


I pulled this to test. First thing I notice is the following error on search.php:

Fatal error: Default value for parameters with a class type hint can only be NULL in C:\xampp\htdocs\EveScoutRescue\class\leaderboard.class.php on line 19

I can't move beyond that, and I don't know what this means. Can you look into this and advise? Thanks!

**Comment by Thricehappy** [comment]
Now I get this error:

Catchable fatal error: Argument 1 passed to Leaderboard::getTopPilotsWeek() must be an instance of int, integer given, called in C:\xampp\htdocs\EveScoutRescue\esrc\search.php on line 208 and defined in C:\xampp\htdocs\EveScoutRescue\class\leaderboard.class.php on line 82

Seems like the type-hinting thing is not working as expected on my machine. Do I maybe have the wrong version of PHP running locally?

**Comment by bikerunner** [comment]
I removed the type definition for method parameters now. Please try again. Need to check PHP system settings after wards with a separate test script.

**Comment by Thricehappy** [comment]
Realized I was running PHP 5.6 on my localhost environment. Tried upgrading to 7.1 and now everything is messed up. This might take a bit for me to get things figured out. Sorry.

**Comment by Thricehappy** [comment]
OK. I got rolled back to PHP 5.6 on localhost. Have to get upgraded later, I guess.

search.php working good now with one exception. On Hall of Help section, I get this error:

Notice: Undefined variable: lastDays in C:\xampp\htdocs\EveScoutRescue\class\leaderboard.class.php on line 121

If you can fix that, I think we're close. Thanks!

**Pull request merged**
